In [51]:
import numpy as np
import pandas as pd

In [52]:
df = pd.read_csv("C:/Users/Sarthak/Downloads/echocardiogram (1).csv")
df.head()

survival  alive   age  pericardialeffusion  fractionalshortening    epss  \
0      11.0    0.0  71.0                  0.0                 0.260   9.000   
1      19.0    0.0  72.0                  0.0                 0.380   6.000   
2      16.0    0.0  55.0                  0.0                 0.260   4.000   
3      57.0    0.0  60.0                  0.0                 0.253  12.062   
4      19.0    1.0  57.0                  0.0                 0.160  22.000   

    lvdd  wallmotion-score  wallmotion-index   mult  name  group  aliveat1  
0  4.600              14.0              1.00  1.000  name    1.0       0.0  
1  4.100              14.0              1.70  0.588  name    1.0       0.0  
2  3.420              14.0              1.00  1.000  name    1.0       0.0  
3  4.603              16.0              1.45  0.788  name    1.0       0.0  
4  5.750              18.0              2.25  0.571  name    1.0       0.0

In [53]:
median = df['age'].median()
df['age'].fillna(median, inplace=True)

In [54]:
median = df['fractionalshortening'].median()
df['fractionalshortening'].fillna(median, inplace=True)

In [55]:
median = df['epss'].median()
df['epss'].fillna(median, inplace=True)

In [56]:
dfmedian = df['wallmotion-score'].median()
df['wallmotion-score'].fillna(median, inplace=True)

In [57]:
dfmedian = df['lvdd'].median()
df['lvdd'].fillna(median, inplace=True)

In [58]:
dfmedian = df['mult'].median()
df['mult'].fillna(median, inplace=True)

In [59]:
for i in df.columns:
    print(df[i].unique(),"\t",df[i].nunique())

[1.10e+01 1.90e+01 1.60e+01 5.70e+01 2.60e+01 1.30e+01 5.00e+01 2.50e+01
 1.00e+01 5.20e+01 4.40e+01 5.00e-01 2.40e+01 2.20e+01 1.00e+00 7.50e-01
 5.00e+00 4.80e+01 2.90e+01 2.50e-01 3.60e+01 3.00e+00 2.70e+01 3.50e+01
 3.10e+01 3.20e+01 4.00e+01 4.60e+01 2.00e+00 3.70e+01 1.95e+01 2.00e+01
      nan 7.00e+00 1.20e+01 4.50e+01 5.30e+01 3.80e+01 9.00e+00 4.90e+01
 4.70e+01 4.10e+01 3.30e+01 1.50e+01 3.00e-02 2.30e+01 3.40e+01 2.10e+01
 5.50e+01 4.00e+00 1.25e+00 2.80e+01 1.70e+01 7.50e+00] 	 53
[ 0.  1. nan] 	 2
[71.    72.    55.    60.    57.    68.    62.    46.    54.    77.
 73.    69.    62.529 66.    85.    64.    35.    75.    65.    52.
 47.    63.    61.    80.    70.    79.    56.    67.    81.    59.
 58.    51.    50.    78.    86.    74.    53.    48.   ] 	 38
[ 0.  1. 77. nan] 	 3
[0.26  0.38  0.253 0.16  0.23  0.33  0.34  0.14  0.13  0.45  0.15  0.12
 0.25  0.07  0.09  0.22  0.18  0.17  0.19  0.3   0.205 0.21  0.4   0.61
 0.06  0.51  0.41  0.35  0.27  0.44  0.03  0.04  0

In [60]:
median = df['aliveat1'].median()
df['aliveat1'].fillna(median, inplace=True)

In [61]:
median = df['group'].median()
df['group'].fillna(median, inplace=True)

In [62]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for i in df.columns:
    df[i] = le.fit_transform(df[i])

In [63]:
X = df.iloc[:,:12].values
y = df.iloc[:,12].values

In [69]:
from sklearn.model_selection import train_test_split as tts
from sklearn.tree import DecisionTreeClassifier

In [75]:
X_train, X_test, y_train, y_test = tts(X, y, test_size = 0.2)

In [76]:
clf = DecisionTreeClassifier()
clf.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [77]:
print(clf.predict(X_test))
clf.score(X_test, y_test)

[0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0]


0.8518518518518519

In [78]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators = 3)
rf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=3, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [79]:
print(rf.predict(X_test))
rf.score(X_test, y_test)


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0]


0.8148148148148148

In [80]:
from sklearn import svm

sv = svm.SVC(kernel = 'linear')
sv.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [81]:
print(sv.predict(X_test))
sv.score(X_test, y_test)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0]


0.7777777777777778